name: Tests

on:
  push:
    branches:
      - 'main'

  pull_request:


jobs:
  benchopt_dev:
    uses: benchopt/template_benchmark/.github/workflows/test_benchmarks.yml@main
    with:
      benchopt_branch: benchopt@main
  benchopt_release:
    uses: benchopt/template_benchmark/.github/workflows/test_benchmarks.yml@main
    with:
      benchopt_version: latest
  lint:
    uses: benchopt/template_benchmark/.github/workflows/lint_benchmarks.yml@main
